### ISSUE TITLE
scan for duplicates on folder tooltip bug

### ISSUE THREAD

**Issue by ondrejlohnisky** [cloud-py-api/mediadc#104]
**Describe the bug**
Missing icon.

**Screenshots**
![Screenshot_11](https://user-images.githubusercontent.com/28301603/211461700-d48522bb-fb3a-4b40-9585-12385693bd34.png)

**Comment by andrey18106** [comment]
@ondrejlohnisky Hi! Fixed this in the latest release. Closing as complete. If there are any issues, feel free to reopen this or create a new one.
