### ISSUE TITLE
Missing "configuration" tab as an administrator 

### ISSUE THREAD

**Issue by Chuckame** [cloud-py-api/mediadc#122]
**Describe the bug**
Unable to finalize installation since the configuration tab is missing, so I'm unable to click on the install button as said in the wiki

**To Reproduce**
I don't know if toits reproducible, but just install cloud py api, and mediadc, then configuration section is not visible 

**Expected behavior**
Configuration tab available 

**Screenshots**
![IMG_20230313_003346](https://user-images.githubusercontent.com/16419143/224580770-d2f12d06-923c-4f0a-9f1c-ccc73cb345a6.jpg)

**Desktop (please complete the following information):**
 - OS unraid / docker
 - CPU x86 Intel j4105
 - Nextcloud version 25.0.3
 - Database configuration mysql
 - Python version dont know, bundled? Default config 
 - MediaDC version 0.3.3
 - `cloud_py_api` version 0.1.5

**Comment by andrey18106** [comment]
@Chuckame Hi! Configuration page removed since the 0.3.0 version. Instead added pre-compiled Python binaries, that must be downloaded on app install (or enable). But we kept usage from sources, as it was before, with only difference - administrators must install all needed Python packages manually (see [wiki notice](https://github.com/cloud-py-api/mediadc/wiki#mediadc-030-important-notice)).

The screenshot in wikis of the configuration page is for the old MediaDC versions.

**Comment by Chuckame** [comment]
Thanks for the explanation, do I don't understand why the duplicate detection task is still pending :/

**Comment by andrey18106** [comment]
Yes, this is known issue, check out these ones: https://github.com/cloud-py-api/mediadc/issues/100, https://github.com/cloud-py-api/mediadc/issues/101.

If no python binaries downloaded for some reason - try manual installation like in wiki notice I mentioned before.

**Comment by Chuckame** [comment]
Command not working: `/usr/bin/python3: No module named pip` I'm searching, but if you have idea, it should be great

**Comment by andrey18106** [comment]
@Chuckame Manual installation requires python3 and pip installed in system (usually by `apt install python3-pip` command or similar with another system package manager, e.g. `apk add py3-pip` on Apline, depends on your OS).

**Comment by Chuckame** [comment]
Ok so I'll make a PR to clarify all those details. Thanks!

Le lun. 13 mars 2023 à 20:06, Andrey Borysenko ***@***.***> a
écrit :

**Comment by Chuckame** [comment]
Even with freshly deployed 0.3.4

**Comment by bigcat88** [comment]
Can you remove `mediadc` directory in `appdata_xxx` and reinstall new version that was released today?
Instead of one file there should be directory after that - maybe that will fix running in standard mode with bundled python.

**Comment by Chuckame** [comment]
do i reinstall requirements ?

**Comment by bigcat88** [comment]
no, just use it in the default mode with prebuilt binaries

**Comment by Chuckame** [comment]
Ok, i re-check prebuilt binaries

**Comment by Chuckame** [comment]
Oh, it's working !!! It found some duplicates. Btw, 2 questions:
- do i still have to install pip since prebuilt binaries work now ?
- is it normal that the ui is not refreshed ? (progress keeps 0 and goes directly to finished, total of 44 photos scanned for this folder)

**Comment by bigcat88** [comment]
> * do i still have to install pip since prebuilt binaries work now ?

no, that mode is for development mostly



> * is it normal that the ui is not refreshed ? (progress keeps 0 and goes directly to finished, total of 44 photos scanned for this folder)

UI will be refresh after each folder it finishes. In future will will do to refresh after `N` files, where `N` is an option.

**Comment by Chuckame** [comment]
Oh, permission denied to remove a duplicate, nothing in logs, all files are chown with www-data user (uid/gid 33)
> no, that mode is for development mostly
Perfect !
> UI will be refresh after each folder it finishes [...]
Ok thanks for the info

**Comment by bigcat88** [comment]
can you delete those files with `Files` app?

**Comment by Chuckame** [comment]
I haven't the option to remove the file, only copy or move 😮

**Comment by Chuckame** [comment]
But I can remove other files, so thanks, now I have work to remove all the duplicates 😁
