### ISSUE TITLE
Stuck on Pending for 10 days

### ISSUE THREAD

**Issue by YouveGotMeowxy** [cloud-py-api/mediadc#163]
![image](https://user-images.githubusercontent.com/39491297/236954757-e48d8636-6fe8-4c5e-a78a-f57fe9cc73b3.png)

I have tried setting Use pre-compiled Python binaries to both checked and unchecked but it never proceeds.

I installed MDC and the python api both via the NC Apps tab.

I'm using the latest NC, and all apps fully updated. 

Any idea how to resolve?

**Comment by beanlover** [comment]
Are you using the "snap" version by any chance? I am encountering the same thing but the log file is trying to run "main.py" from the appdata folder instead of where the app is actually installed.

**Comment by andrey18106** [comment]
@YouveGotMeowxy Could you send us your configuration please. Have you tried manual installation and usage from Python sources? Could you also verify if binaries downloaded correctly (in appdata folder: mediadc/binaries/).

**Comment by YouveGotMeowxy** [comment]
I was reading up on some similar issues and they were saying mediadc should be installed after cloud python api, and originally i installed them in the opposite order, so I uninstalled both, restarted container, then installed the api addon first, then mdc, restarted container, and it seems to have fixed it. If it stops again for some reason I'll report back. :)

I suppose I'll close this issue for now since it seems to have "resolved itself".
