### ISSUE TITLE
NC30 - compatible ?

### ISSUE THREAD

**Issue by moritzmofi** [cloud-py-api/mediadc#255]
is the actual Version  0.3.9 compatible to Nextcloud 30?

**Comment by andrey18106** [comment]
Yes, but UI needs update, I'll do that later this week.

**Comment by andrey18106** [comment]
> > Yes, but UI needs update, I'll do that later this week.
> 
> are there any news?

Sorry for delay, will release update tomorrow (https://github.com/cloud-py-api/mediadc/pull/262).

**Comment by moritzmofi** [comment]
it works - thanx
