### ISSUE TITLE
Add Plesk-specific PHP configuration instructions to the Wiki

### ISSUE THREAD

**Issue by kzorluoglu** [cloud-py-api/mediadc#265]
### Context
I noticed that Plesk users require additional steps to correctly configure the MediaDC application when using Nextcloud. However, since GitHub does not allow forking or branching the Wiki repository, I am unable to contribute these changes directly. Therefore, I am submitting this issue with the proposed changes.

### Proposed Wiki Changes
Below is the content that I suggest adding to the **Installation** section of the wiki:

---

#### Configuring PHP on Plesk
If you are using Nextcloud installed via **Plesk**, you must configure the correct PHP interpreter path in the MediaDC settings. Follow these steps:

1. After enabling MediaDC, navigate to the **Admin Settings** in Nextcloud.
2. In the MediaDC configuration section:
   - Enable the **"Use path to PHP interpreter for Python"** option.
   - Set the **Full path to PHP interpreter for Python** to:
     ```
     /opt/plesk/php/8.x/bin/php
     ```
     Replace `8.x` with your specific PHP version (e.g., `8.2`).
3. Save your settings and verify that MediaDC functions as expected.

This will ensure that MediaDC can correctly execute PHP-related tasks on a Plesk-managed system.

---

### Why This Is Important
Without these instructions, Plesk users might encounter issues due to incorrect PHP configurations, as the default PHP path is not compatible with Plesk setups.

---

Thank you for reviewing this suggestion.

**Comment by andrey18106** [comment]
Thank you for the notes, you can find them now here: https://github.com/cloud-py-api/mediadc/wiki/Installation#configuring-php-on-plesk
