### ISSUE TITLE
Request for 'export results'

### ISSUE THREAD

**Issue by schmurgel-tg** [cloud-py-api/mediadc#60]
It would be nice if I could export the results of a task.
My first task finished with over 11k groups. It would help, if I could simply export those results, for example into a xml file, with the groups and filename (full name) as elements, or in a plain textfile.

**Comment by bigcat88** [comment]
[#48c1b033a08da7c3236a28c457946d04b0737c26](https://github.com/andrey18106/mediadc/commit/48c1b033a08da7c3236a28c457946d04b0737c26)

**Comment by andrey18106** [comment]
@schmurgel-tg Hi! Added task export option in v0.3.2. Closing this issue as completed.

If you have any additions - you're welcome.
