### ISSUE TITLE
"Not enough permitions to delete file"

### ISSUE THREAD

**Issue by GrumpyMeow** [cloud-py-api/mediadc#62]
**Describe the bug**
I keep getting the error message "Not enough permitions to delete file". But i don't know how to resolve the issue.

Which user is being used for deletion?

**Comment by andrey18106** [comment]
@GrumpyMeow Current authorized user is used for file deletion. Can you check logs for related messages after trying to delete such files? Are these files shared or you can't delete your own files?

**Comment by andrey18106** [comment]
Closing as stale. If have any questions - feel free to reopen.
