### ISSUE TITLE
How to Install in truenas scale

### ISSUE THREAD

**Issue by SadBoen** [cloud-py-api/mediadc#92]
Hi, I have install nextcloud in truenas scale by truechart.
and I don't know to install this app manually, and install by web gui's button is fales.

Thank you very much!

**Comment by bigcat88** [comment]
`TrueNAS Scale` probably should work with beta.
Try it and say does it work for you or not.

`TrueNAS CORE` is not supported at all(for now)

**Comment by andrey18106** [comment]
@SadBoen Hi! If there are any additional question - feel free to write here or open a new issue. For now, closing as stale.
